<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\Account;

//use App\User;

class Contact extends Model {

	protected $table = 'contacts';
	protected $fillable = [
		'id',
		'account_id',
		'name',
		'first_name',
		'last_name',
		'cpf',
		'email',
		'phone',
		'site',
		'address',
		'city',
		'state',
		'country',
		'type',
		'company',
		'zip_code',
		'cep',
		'neighborhood',
		'job_position',
		'acess_profile',
		'date_birth',
		'profession',
		'religion',
		'etinicity',
		'naturality',
		'sexual_orientation',
		'schollarity',
		'income',
		'civil_state',
		'kids',
		'hobbie',
		'instagram',
		'facebook',
		'linkedin',
		'twitter',
		'lead_source',
	];
	protected $hidden = [
	];

	//RELACIONAMENTOS
	public function account() {
		return $this->belongsTo(Account::class, 'account_id', 'id');
	}

	public function contracts() {
		return $this->hasMany(Contract::class, 'id', 'contract_id');
	}

	public function companies() {
		return $this->belongsToMany(Company::class);
	}

	public function opportunities() {
		return $this->hasMany(Opportunity::class, 'contact_id', 'id');
	}

	public function tasks() {
		return $this->hasMany(Task::class, 'id', 'contact_id');
	}

	public function user() {
		return $this->belongsTo(User::class, 'id', 'contact_id');
	}

//FUNÇÕES PÚBLICAS
	public static function returnGenderTypes() {
		return [
			'masculino',
			'feminino',
			'não-binário',
		];
	}

	public static function returnHobbie() {
		return [
			'artes plásticas e visuais',
			'dança',
			'cinema e séries',
			'comer',
			'cozinhar',
			'ler e escrever',
			'línguas',
			'música',
			'teatro',
			'trabalho voluntário',
			'video game',
		];
	}

	public static function returnReligion() {
		return [
			'agnóstico',
			'ateu',
			'católico',
			'espírita',
			'matriz africana',
		];
	}

	public static function returnEtinicity() {
		return [
			'branco ou Caucasiano',
			'amarelo ou Mongol',
			'negro',
			'indígina',
			'matriz africana',
		];
	}
	public static function returnContactTypes() {
		return [
			'cliente',
			'administrador',
			'funcionário',
			'fornecedor',
			'parceiro',
			'Dono',
			];
	}

	public static function returnProfession() {
		return [
			'Administrador',
			'Administrador público',
			'Agropecuarista',
			'Contabilista',
			'Economista',
			'Especialista em comércio exterior',
			'Chef',
			'Gerente comercial',
			'Gestor de recursos humanos',
			'Gestor de turismo',
			'Gestor público',
			'Hoteleiro',
			'Piloto de avião',
			'Turismólogo',
			'Artes e Design',
			'Animador',
			'Arquiteto',
			'Artista plástico',
			'Ator',
			'Dançarino',
			'Designer',
			'Designer de games',
			'Designer de interiores',
			'Designer de moda',
			'Fotógrafo',
			'Historiador da arte',
			'Músico',
			'Produtor cênico',
			'Produtor fonográfico',
			'Agrônomo',
			'Bioquímico',
			'Biotecnólogo',
			'Ecologista',
			'Geofísico',
			'Geólogo',
			'Gestor ambiental',
			'Veterinário',
			'Meteorologista',
			'Oceanógrafo',
			'Zootecnólogo',
			'Analista e desenvolvedor de sistemas',
			'Astrônomo',
			'Cientista da computação',
			'Estatístico',
			'Físico',
			'Gestor da tecnologia da informação',
			'Matemático',
			'Nanotecnólogo',
			'Químico',
			'Advogado',
			'Arqueólogo',
			'Cooperativista',
			'Filósofo',
			'Geógrafo',
			'Historiador',
			'Linguista',
			'Museologista',
			'Pedagogo',
			'Professor',
			'Psicopedagogo',
			'Relações internacionais',
			'Sociólogo',
			'Teólogo',
			'Tradutor e intérprete',
			'Comunicação e Informação',
			'Arquivologista',
			'Biblioteconomista',
			'Educomunicador',
			'Jornalista',
			'Produtor audiovisual',
			'Produtor cultural',
			'Produtor editorial',
			'Produtor multimídia',
			'Produtor publicitário',
			'Publicitário',
			'Radialista',
			'Relações públicas',
			'Secretária',
			'Secretária executiva',
			'Agricultor',
			'Construtor civil',
			'Construtor naval',
			'Engenheiro acústico',
			'Engenheiro aeronáutico',
			'Engenheiro agrícola',
			'Engenheiro ambiental e sanitário',
			'Engenheiro biomédico',
			'Engenheiro civil',
			'Engenheiro da computação',
			'Engenheiro de alimentos',
			'Engenheiro de biossistemas',
			'Engenheiro de controle e automação',
			'Engenheiro de energia',
			'Engenheiro de inovação',
			'Engenheiro de materiais',
			'Engenheiro de minas',
			'Engenheiro de pesca',
			'Engenheiro de petróleo',
			'Engenheiro de produção',
			'Engenheiro de segurança do trabalho',
			'Engenheiro de sistemas',
			'Engenheiro de software',
			'Engenheiro de telecomunicações',
			'Engenheiro de transporte e mobilidade',
			'Engenheiro elétrico',
			'Engenheiro eletrônico',
			'Engenheiro físico',
			'Engenheiro florestal',
			'Engenheiro hídrico',
			'Engenheiro mecânico',
			'Engenheiro mecatrônico',
			'Engenheiro naval',
			'Engenheiro químico',
			'Gestor da qualidade',
			'Minerador',
			'Silvicultor',
			'Saúde e Bem-Estar',
			'Biomédico',
			'Dentista',
			'Educador físico',
			'Enfermeiro',
			'Esteticista',
			'Farmacêutico',
			'Fisioterapeuta',
			'Fonoaudiólogo',
			'Gerontólogo',
			'Gestor em saúde',
			'Gestor hospitalar',
			'Médico',
			'Musicoterapeuta',
			'Nutricionista',
			'Psicólogo',
			'Radiologista',
			'Terapeuta ocupacional',
			'outro',
		];
	}

	public static function returnJob_position() {
		return [
			'Administrador',
			'Administrador público',
			'Agropecuarista',
			'Contabilista',
			'Economista',
			'Especialista em comércio exterior',
			'Chef',
			'Gerente comercial',
			'Gestor de recursos humanos',
			'Gestor de turismo',
			'Gestor público',
			'Hoteleiro',
			'Piloto de avião',
			'Turismólogo',
			'Artes e Design',
			'Animador',
			'Arquiteto',
			'Artista plástico',
			'Ator',
			'Dançarino',
			'Designer',
			'Designer de games',
			'Designer de interiores',
			'Designer de moda',
			'Fotógrafo',
			'Historiador da arte',
			'Músico',
			'Produtor cênico',
			'Produtor fonográfico',
			'Agrônomo',
			'Bioquímico',
			'Biotecnólogo',
			'Ecologista',
			'Geofísico',
			'Geólogo',
			'Gestor ambiental',
			'Veterinário',
			'Meteorologista',
			'Oceanógrafo',
			'Zootecnólogo',
			'Analista e desenvolvedor de sistemas',
			'Astrônomo',
			'Cientista da computação',
			'Estatístico',
			'Físico',
			'Gestor da tecnologia da informação',
			'Matemático',
			'Nanotecnólogo',
			'Químico',
			'Advogado',
			'Arqueólogo',
			'Cooperativista',
			'Filósofo',
			'Geógrafo',
			'Historiador',
			'Linguista',
			'Museologista',
			'Pedagogo',
			'Professor',
			'Psicopedagogo',
			'Relações internacionais',
			'Sociólogo',
			'Teólogo',
			'Tradutor e intérprete',
			'Comunicação e Informação',
			'Arquivologista',
			'Biblioteconomista',
			'Educomunicador',
			'Jornalista',
			'Produtor audiovisual',
			'Produtor cultural',
			'Produtor editorial',
			'Produtor multimídia',
			'Produtor publicitário',
			'Publicitário',
			'Radialista',
			'Relações públicas',
			'Secretária',
			'Secretária executiva',
			'Agricultor',
			'Construtor civil',
			'Construtor naval',
			'Engenheiro acústico',
			'Engenheiro aeronáutico',
			'Engenheiro agrícola',
			'Engenheiro ambiental e sanitário',
			'Engenheiro biomédico',
			'Engenheiro civil',
			'Engenheiro da computação',
			'Engenheiro de alimentos',
			'Engenheiro de biossistemas',
			'Engenheiro de controle e automação',
			'Engenheiro de energia',
			'Engenheiro de inovação',
			'Engenheiro de materiais',
			'Engenheiro de minas',
			'Engenheiro de pesca',
			'Engenheiro de petróleo',
			'Engenheiro de produção',
			'Engenheiro de segurança do trabalho',
			'Engenheiro de sistemas',
			'Engenheiro de software',
			'Engenheiro de telecomunicações',
			'Engenheiro de transporte e mobilidade',
			'Engenheiro elétrico',
			'Engenheiro eletrônico',
			'Engenheiro físico',
			'Engenheiro florestal',
			'Engenheiro hídrico',
			'Engenheiro mecânico',
			'Engenheiro mecatrônico',
			'Engenheiro naval',
			'Engenheiro químico',
			'Gestor da qualidade',
			'Minerador',
			'Silvicultor',
			'Saúde e Bem-Estar',
			'Biomédico',
			'Dentista',
			'Educador físico',
			'Enfermeiro',
			'Esteticista',
			'Farmacêutico',
			'Fisioterapeuta',
			'Fonoaudiólogo',
			'Gerontólogo',
			'Gestor em saúde',
			'Gestor hospitalar',
			'Médico',
			'Musicoterapeuta',
			'Nutricionista',
			'Psicólogo',
			'Radiologista',
			'Terapeuta ocupacional',
			'outro',
		];
	}

}
